behaviors:
  My Behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 32768
      learning_rate: 0.0001
      beta: 0.005
      epsilon: 0.15
      lambd: 0.97
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: nature_cnn
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 10
    max_steps: 5000000
    time_horizon: 2000
    summary_freq: 5000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 10000
      team_change: 5000
      swap_steps: 2000
