behaviors:
  My Behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 16384
      learning_rate: 0.0003
      beta: 0.002
      epsilon: 0.3
      lambd: 0.96
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.8
      curiosity:
        gamma: 0.99
        strength: 0.2
    keep_checkpoints: 5
    max_steps: 3000000
    time_horizon: 1000
    summary_freq: 2000
    self_play:
      window: 8
      play_against_latest_model_ratio: 0.4
      save_steps: 5000
      team_change: 2000
      swap_steps: 1500
